/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

  public static void main(String[] args) {
    Palindrome palindrome = new Palindrome();
    palindrome.isPalindrome("Was it a car or a cat I saw?");
    System.out.println(palindrome.isPalindrome("baac"));
  }
}
